In [94]:
import keras

In [95]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from keras.wrappers.scikit_learn import KerasClassifier

In [96]:
!ls ~/library

data.csv  README.md  Untitled 1.ipynb  Untitled.ipynb  winequality-white.csv


In [97]:
dataset = pd.read_csv("~/library/winequality-white.csv",sep=";")

In [98]:
dataset.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  4898.000000  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267     5.877909  
std       0.151001     0.114126     1.230621     0.885639  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.090000     0.410000     9.500000     5.000000  
50%       3.180000     0.470000    10.400000     6.000000  
75%       3.280000     0.550000    11.400000     6.000000  
max       3.820000     1.080000    14.200000     9.000000

In [99]:
print(dataset.isnull().sum())

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64


In [100]:
X = dataset.iloc[:,0:11].values

In [101]:
Y = dataset.iloc[:,11].values

In [102]:
encoder = LabelEncoder()
encoder.fit(Y)
print(Y)

[6 6 6 ... 6 7 6]


In [103]:
from keras.utils import np_utils
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

In [104]:
from sklearn.preprocessing import Imputer

In [105]:
print(dummy_y[1])
print(X[1])

[0. 0. 0. 1. 0. 0. 0.]
[6.30e+00 3.00e-01 3.40e-01 1.60e+00 4.90e-02 1.40e+01 1.32e+02 9.94e-01
 3.30e+00 4.90e-01 9.50e+00]


In [106]:
from sklearn.model_selection import train_test_split

In [107]:
X_train,X_test,Y_train,Y_test = train_test_split(X,dummy_y,test_size = 0.20,random_state = 0)

In [108]:
import keras

In [109]:
from keras.models import Sequential

In [110]:
from keras.layers import Dense

In [111]:
classifier = Sequential()

In [112]:
classifier.add(Dense(output_dim=6,activation = 'relu', input_dim = 11))

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6)`
  if __name__ == '__main__':


In [113]:
classifier.add(Dense(output_dim=6,activation='relu'))

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6)`
  if __name__ == '__main__':


In [114]:
classifier.add(Dense(output_dim=6,activation='relu'))

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6)`
  if __name__ == '__main__':


In [115]:
classifier.add(Dense(output_dim=7,activation='softmax'))

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=7)`
  if __name__ == '__main__':


In [116]:
classifier.compile(optimizer = 'adam',loss = 'mean_squared_error')

In [121]:
classifier.fit(X_train, Y_train, nb_epoch=100)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  if __name__ == '__main__':


Epoch 1/100
3918/3918 [==============================] - 1s 342us/step - loss: 0.1746
Epoch 2/100
3918/3918 [==============================] - 0s 120us/step - loss: 0.1157
Epoch 3/100
3918/3918 [==============================] - 0s 114us/step - loss: 0.1155
Epoch 4/100
3918/3918 [==============================] - 0s 115us/step - loss: 0.1146
Epoch 5/100
3918/3918 [==============================] - 0s 107us/step - loss: 0.1133
Epoch 6/100
3918/3918 [==============================] - 1s 129us/step - loss: 0.1131
Epoch 7/100
3918/3918 [==============================] - 0s 114us/step - loss: 0.1056
Epoch 8/100
3918/3918 [==============================] - 0s 125us/step - loss: 0.0967
Epoch 9/100
3918/3918 [==============================] - 0s 117us/step - loss: 0.0960
Epoch 10/100
3918/3918 [==============================] - 0s 116us/step - loss: 0.0957
Epoch 11/100
3918/3918 [==============================] - 0s 106us/step - loss: 0.0955
Epoch 12/100
3918/3918 [============================

3918/3918 [==============================] - 0s 94us/step - loss: 0.0855
Epoch 96/100
3918/3918 [==============================] - 0s 93us/step - loss: 0.0856
Epoch 97/100
3918/3918 [==============================] - 0s 85us/step - loss: 0.0862
Epoch 98/100
3918/3918 [==============================] - 0s 96us/step - loss: 0.0862
Epoch 99/100
3918/3918 [==============================] - 0s 114us/step - loss: 0.0858
Epoch 100/100
3918/3918 [==============================] - 0s 99us/step - loss: 0.0856


In [122]:
y_pred = classifier.predict(X_test)

In [126]:
y_pred[1]

array([8.8061980e-04, 2.4988901e-02, 3.5958734e-01, 5.0803971e-01,
       9.5965385e-02, 1.0538167e-02, 6.0322991e-10], dtype=float32)

In [144]:

score = classifier.evaluate(X_test, Y_test)


980/980 [==============================] - 0s 68us/step


In [145]:
score

0.09135198720863887

In [143]:
Y_test

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)